### ISSUE TITLE
后端：确定数据库字段

### ISSUE THREAD

**Issue by wyl1232792** [wyl1232792/SE-Service-Exchange#5]

**Comment by 510453684** [comment]
用php写一段代码后怎么编译运行一下试试？

**Comment by 510453684** [comment]
需要再装什么软件吗？

**Comment by zw1003855799** [comment]
<!DOCTYPE html>  放在PHP代码的开头，是不是和c语言中的头文件类似，吴教授，求释疑。

**Comment by wyl1232792** [comment]
<!DOCTYPE html> 是用来声明html5的，和php没有关系，就当成一个既定的语句吧

**Comment by wyl1232792** [comment]
不用编译呀 你们开了xampp就可以打网址了

**Comment by chenhao1123** [comment]
宁是想自己写点简单的php试一下

**Comment by wyl1232792** [comment]
不用laravel的话 在public里面开个再新建个php比如名字是nx.php 那么地址栏就输入localhost/nx.php
话说一定不要再master里面改！

**Comment by 510453684** [comment]
数据库字段
goods
	user_ID
	good_ID
	good_name
	information
	reason（出售原因）
	new_price（买入价）
	buy_time
	condition（成色，英文是不是这个？）
	picture
	guarantee（是否过保）
services

categories
	condition（成色）
	brand
	trade_way
	contract_way（联系方式）
requests
	
quotes
	price
	bargain（是否接受议价）
trades
	trade_way(交易方式)
	place（交易地点）
	time（能接受的交易时间）
follows
	goods
	people
	market
marks
	user_ID
	goods_ID

**Comment by zw1003855799** [comment]
字段
name
id
password
address
telephone_number

if people want to sell goods:
the_name_of_goods
introduction
price

if people want to buy goods:
the_goods_he_want
price_he_can_offer


the_way_of_trade
time
place

**Comment by wyl1232792** [comment]
一阶段完成
